production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/release_*
  required_contexts: ["ci"]
  environment: staging
  production_environment: false

dev:
  auto_deploy_on: refs/heads/dev
  required_contexts: ["ci"]
  environment: dev
  production_environment: false
