production:
  environment: production
  production_environment: true
  auto_deploy_on: refs/tags/v*
  required_contexts: ["deliverybot/promotion"]

qa:
  auto_deploy_on: refs/heads/release_*
  environment: qa
  production_environment: false

dev:
  auto_deploy_on: refs/tags/v*
  environment: dev
  production_environment: false
  ref: ${{ ref }}