steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image:test_tag', '-t', 'gcr.io/$PROJECT_ID/quickstart-image:test_tag2', '.' ]
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'