name: TEST 2
on:
  push:
    branches:
    - dev

env:
  RELEASE_VERSION: v2.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
          
      # Tag
      - name: Github Tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          # Required for permission to tag the repo.
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Comma separated list of branches (bash reg exp accepted) that will generate the release tags. Other branches and pull-requests generate versions postfixed with the commit hash and do not generate any tag. Examples: `master` or `.*` or `release.*,hotfix.*,master`...
          release_branches: dev


