name: TEST 2
on:
  push:
    branches:
    - dev

jobs:
  test5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install, build, and test
        run: |
          echo 'ok'
