name: TEST 2
on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
          
      # Tag
      - name: Github Tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          # Required for permission to tag the repo.
          github_token: ${{secrets.GITHUB_TOKEN}}

