name: TEST 2
on: 
  workflow_dispatch:
    inputs:
      deployTo: 
        description: 'Environment to deploy to'
        required: true
        default: dev

env:
  PROVISIONER_APP_ID: fff-provisioner-apps

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
                
      - if: contains(env.TAG_NAME, 'feature') && github.event.inputs.deployTo == 'dev'
        run: |
          echo "Environment: ${{ github.event.inputs.deployTo }}"
          echo "Tag: $TAG_NAME"



