name: TEST 2
on:
  push:
    branches:
    - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
          


