name: TEST 2
on: workflow_dispatch

env:
  PROVISIONER_APP_ID: fff-provisioner-apps

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
          
      - if: contains(BRANCH_NAME, 'master') === true
        run: echo "$BRANCH_NAME"



