name: TEST 2
on: 
  workflow_dispatch:
    inputs:
      deployTo: 
        description: 'Environment to deploy to'
        required: true
        default: dev

env:
  PROVISIONER_APP_ID: fff-provisioner-apps
  ENVIRONMENT: dev

jobs:
  test:
    if: contains(github.ref, 'master') && github.event.inputs.deployTo == $ENVIRONMENT

    runs-on: ubuntu-latest
    steps:
      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
            
      - name: Echo values
        run: |
          echo "Environment: ${{ github.event.inputs.deployTo }}"
          echo "Tag: $TAG_NAME"

      # Get branch name to use for tag
      - name: Extract Branch Name2
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"

      # Get branch name to use for tag
      - name: Extract Branch Name3
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"

