name: 'Deploy'
on: ['deployment']

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deployment pending
      uses: deliverybot/status@master
      with:
        state: pending
        token: ${{ secrets.GITHUB_TOKEN }}

# do your deployment here, using whatever tooling you like:

    - name: Extract Branch Name
      run: echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*_})"

    - name: 'Deploy ${{ github.event.deployment.environment }}'
      run: |
        if ${{ github.event.deployment.environment }} == 'development'
        then
          echo "This is the - ${{ github.event.deployment.environment }} - environment"
        elif ${{ github.event.deployment.environment }} == 'qa'
        then
          echo "This is the - ${{ github.event.deployment.environment }} - environment"
        else
          echo "This is the - ${{ github.event.deployment.environment }} - environment"
        fi

    - name: deployment success
      if: success()
      uses: deliverybot/status@master
      with:
        state: success
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: deployment failure
      if: failure()
      uses: deliverybot/status@master
      with:
        state: failure
        token: ${{ secrets.GITHUB_TOKEN }}