# This is a basic workflow to help you get started with Actions

name: Deploy on Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ published ]
    
# LIST OF ENV VARIABLES
env:
  EVENTPATH: ${{github.event_path	}}
  WORKFLOW: ${{ github.workflow}}
  JOB: ${{ github.job }}
  RUN_ID: ${{ github.run_id }}
  RUN_NUM:  ${{ github.run_number }}
  ACTOR: ${{ github.actor }}
  REPO: ${{github.repository}}
  OWNER: ${{github.repository_owner}}
  EVENT_NAME: ${{github.event_name}}
  SHA: ${{github.sha}}
  REF: ${{github.ref}}
  WORKFLOW_REF: ${{github.event.deployment.ref}}
  HEAD_REF: ${{github.head_ref}}
  BASE_REF: ${{github.base_ref}}
  TOKEN: ${{github.token}}
  WORKSPACE: ${{github.workspace}}
  ACTION: ${{github.action}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Extract Branch Name
      run: echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*_})"
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo $EVENTPATH
        echo $WORKFLOW
        echo $JOB
        echo $RUN_ID
        echo $RUN_NUM
        echo $ACTOR
        echo $REPO
        echo $OWNER
        echo $EVENT_NAME
        echo $SHA
        echo $REF
        echo $WORKFLOW_REF
        echo $HEAD_REF
        echo $BASE_REF
        echo $TOKEN
        echo $WORKSPACE
        echo $ACTION
        echo $TAG_NAME