name: TRIGGER WORKFLOW
on: 
  workflow_dispatch:
    inputs:
      deployTo: 
        description: 'Environment to deploy to'
        required: true
        default: dev
      bump:
        description: 'Choose between: patch, minor, major'
        required: true
        default: patch

env:
  EVENTPATH: ${{github.event_path	}}
  WORKFLOW: ${{ github.workflow}}
  JOB: ${{ github.job }}
  RUN_ID: ${{ github.run_id }}
  RUN_NUM:  ${{ github.run_number }}
  ACTOR: ${{ github.actor }}
  REPO: ${{github.repository}}
  OWNER: ${{github.repository_owner}}
  EVENT_NAME: ${{github.event_name}}
  SHA: ${{github.sha}}
  REF: ${{github.ref}}
  WORKFLOW_REF: ${{github.event.deployment.ref}}
  HEAD_REF: ${{github.head_ref}}
  BASE_REF: ${{github.base_ref}}
  TOKEN: ${{github.token}}
  WORKSPACE: ${{github.workspace}}
  ACTION: ${{github.action}}

jobs:
  workflowTrigger:
    if: contains(github.ref, 'master') || contains(github.event.inputs.deployTo, 'dev')

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      # Get branch name to use for tag
      - name: Extract Branch Name
        run: |
          echo "::set-env name=TAG_NAME::$(echo ${GITHUB_REF##*/})"
            
      - name: Echo values
        run: |
          echo "Environment: ${{ github.event.inputs.deployTo }}"
          echo "Tag: $TAG_NAME"

      - name: SHA
        run: |
          echo "${{github.sha}}"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.inputs.bump }}
          WITH_V: true

      - name: New tag name
        run: |
          echo "$new_tag"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false

